/*1. Criação das tabelas*/

CREATE TABLE LABDATABASE.INSTRUTOR (
    ID_INSTRUTOR     NUMBER NOT NULL,
    NOME             VARCHAR2(120) NOT NULL,
    ESPECIALIDADE    VARCHAR2(100),
    TELEFONE         VARCHAR2(20),
    EMAIL            VARCHAR2(100),
    CONSTRAINT INSTRUTOR_PK PRIMARY KEY (ID_INSTRUTOR)
);

CREATE TABLE LABDATABASE.ALUNO (
    ID_ALUNO         NUMBER NOT NULL,
    NOME             VARCHAR2(120) NOT NULL,
    CPF              VARCHAR2(14) UNIQUE NOT NULL,
    DATA_NASCIMENTO  DATE NOT NULL,
    TELEFONE         VARCHAR2(20),
    CONSTRAINT ALUNO_PK PRIMARY KEY (ID_ALUNO)
);


CREATE TABLE LABDATABASE.TREINO (
    ID_TREINO        NUMBER NOT NULL,
    ID_ALUNO         NUMBER NOT NULL,
    ID_INSTRUTOR     NUMBER NOT NULL,
    TIPO             VARCHAR2(50),
    HORARIO          VARCHAR2(10),
    DIAS_SEMANA      VARCHAR2(50),
    FREQUENCIA       NUMBER DEFAULT 0,
    CONSTRAINT TREINO_PK PRIMARY KEY (ID_TREINO)
);

/* 2. Criação das sequences*/

CREATE SEQUENCE LABDATABASE.INSTRUTOR_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LABDATABASE.ALUNO_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LABDATABASE.TREINO_ID_SEQ START WITH 1 INCREMENT BY 1;

/* 3. Criação dos relacionamentos (FKs)*/

ALTER TABLE LABDATABASE.TREINO ADD CONSTRAINT TREINO_ALUNO_FK
FOREIGN KEY (ID_ALUNO)
REFERENCES LABDATABASE.ALUNO (ID_ALUNO)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.TREINO ADD CONSTRAINT TREINO_INSTRUTOR_FK
FOREIGN KEY (ID_INSTRUTOR)
REFERENCES LABDATABASE.INSTRUTOR (ID_INSTRUTOR)
NOT DEFERRABLE;


/*7. Concessão de permissões de acesso*/

GRANT ALL ON LABDATABASE.INSTRUTOR TO LABDATABASE;
GRANT ALL ON LABDATABASE.ALUNO TO LABDATABASE;
GRANT ALL ON LABDATABASE.TREINO TO LABDATABASE;

ALTER USER LABDATABASE QUOTA UNLIMITED ON USERS;
